text = '''
Keukenhof (lit. 'Kitchen garden'; Dutch pronunciation: [ˈkøːkə(n)ˌɦɔf]), also known as the Garden of Europe, is one of the world's largest flower gardens, situated in the municipality of Lisse, in the Netherlands.[1] According to the official website, Keukenhof Park covers an area of 32 hectares (79 acres) and approximately 7 million flower bulbs are planted in the gardens annually.[2][3] While it is widely known for its Tulips, Keukenhof also features numerous other flowers, including hyacinths, daffodils, lilies, roses, carnations and irises.[4]

Keukenhof is located in the province of South Holland, south of Haarlem and southwest of Amsterdam in the area called the "Dune and Bulb Region" (Duin- en Bollenstreek). It is accessible by bus from Haarlem and Leiden train stations as well as Schiphol. Though its grounds are open year-round for private affairs and festivals, Keukenhof is only open to the general public for a world-renowned 8 week tulip display from mid-March to mid-May,[5] with peak viewing arriving near mid-April, depending on growing season weather, which varies annually. In 2019, 1.5 million people visited Keukenhof,[6] equivalent to 26,000 visitors per day.[7] By comparison, the Rijksmuseum receives an average of 8,000 visitors per day, the Efteling receives 14,000.

Keukenhof is situated on the 15th-century hunting grounds of Slot Teylingen; it was the castle's kitchen garden (in Dutch: keukentuin), providing game, fruit and vegetables. The most noted inhabitant, and beneficiary of the garden was Countess Jacoba van Beieren (1401-1436).[8] In 1638, the estate was purchased by Adriaen Maertensz Block, captain and governor of the Dutch East India Company. In 1641 he had a large manor house constructed, which he named Keukenhof, now known as Castle Keukenhof.[9][10]

In 1857, Baron and Baroness Van Pallandt, at the time owners of the estate, tasked landscape architect Jan David Zocher and his son Louis Paul Zocher, both also designers of Amsterdam's Vondelpark, to restructure the park and grounds around the castle. Those parks, designed in English style, remain the foundations for the gardens.[11][12]

Keukenhof, the park as it is now known, was established in 1949 by a consortium of bulb growers and flower exporters to showcase their products and support the export industry. The garden opened to the public in 1950 and received 200,000 visitors in its first year.[13] It operates under a charitable foundation of Count Carel De Gaaf van Lynden.

Each autumn, 40 gardeners plant the 7 million bulbs, donated to the park by over 100 growers.[14] Planting starts early October and is usually completed by 5 December, around Sinterklaas.[15] The flowerbeds are synchronised to the different bulb flowerings to ensure blooms throughout the duration of park's 8-week opening.[16] To ensure continuous bloom, three bulbs are planted in each location. The shallowest bulb will bloom first for three weeks, followed by the subsequent layers.[17]

In addition to the tulip gardens, Keukenhof features a variety of other gardens. The English landscape garden features winding paths and surprise see-through vistas. The walled area of the historical features archival varieties. In the Nature Garden shrubs and perennials are combined with bulb plants. The Japanese Country Garden is a non-traditional garden in a natural environment.[14] Four pavilions house rotating displays and flower exhibits.

The grounds of Castle Keukenhof[18] are open all year long and are frequently used for festivals such as Castlefest, the Ladies Winternight,[19] and the Christmas Fair.[20] The castle also hosts classical music concerts.

In 2017, Keukenhof received 1.4 million visitors.[21] 20% of the visitors are Dutch, while 40% are from Germany, UK and Belgium.[citation needed] The number of visitors from the USA (10%) and China (8%) has grown over the years.

Keukenhof falls under a charitable foundation of Count Carel De Graaf van Lynden (Stichting Graaf Carel van Lynden). As of January 1, 2016, the foundation owns both Keukenhof and Castle Keukenhof plus the surrounding estate.[29]

The Keukenhof does not receive government subsidies; revenues are generated from ticket sales and the food and beverage licensees on premise. In 2019 Keukenhof generated €25 million in revenue.[30] In 2020, as a consequence of the COVID-19 COVID pandemic and closures to contain it, the park was shut from its scheduled opening day, 21 March until its scheduled closing date, 10 May, costing it an estimated $25 million in revenues.[31]
'''